feat: finish configuration

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -107,3 +107,26 @@ jobs:
           push: true
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
+  
+    deploy:
+    name: Deploy to Target Node & Verify
+    needs: build-and-push
+    if: startsWith(github.ref, 'refs/tags/')
+    runs-on: self-hosted
+    steps:
+      - name: Deploy application via SSH
+        run: |
+          ssh -o StrictHostKeyChecking=no ubuntu@192.168.X.X "sudo systemctl restart task-tracker-docker"
+
+      - name: Verify Deployment (Health Check)
+        run: |
+          echo "Waiting for container to start..."
+          sleep 5
+          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://192.168.88.157/health/alive)
+          
+          if [ "$HTTP_STATUS" -eq 200 ]; then
+            echo "Deployment successful! Service is alive."
+          else
+            echo "Deployment failed! HTTP status: $HTTP_STATUS"
+            exit 1
+          fi
